name: Bug report
description: Report a defect in docs, examples, or reference code
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
    validations:
      required: false
