name: Feature request
description: Propose an enhancement or new instantiation
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What do you want to add?
      description: Describe the feature and why it helps instantiate REE.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal interface / spec impact
      description: Which part of REE_MIN_SPEC does this touch?
    validations:
      required: true
